# Generated by Django 6.0.6 on 2026-07-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otcsale_otcsaleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='source_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('PHARMACY', 'Pharmacy'), ('INPATIENT', 'Inpatient')], max_length=20),
        ),
    ]
