# Generated by Django 6.0.6 on 2026-07-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoice_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='source_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('PHARMACY', 'Pharmacy'), ('INPATIENT', 'Inpatient'), ('PROCEDURE', 'Procedure')], max_length=20),
        ),
    ]
