# Generated by Django 6.0.6 on 2026-07-13 22:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_alter_invoice_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('daily_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('MATERNITY', 'Maternity'), ('PEDIATRIC', 'Pediatric'), ('ICU', 'ICU'), ('HDU', 'High Dependency Unit'), ('SURGICAL', 'Surgical'), ('ISOLATION', 'Isolation'), ('PRIVATE', 'Private Wing')], max_length=20)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('gender_restriction', models.CharField(choices=[('MALE', 'Male Only'), ('FEMALE', 'Female Only'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('default_daily_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('admission_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('admission_type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('ELECTIVE', 'Elective'), ('TRANSFER_IN', 'Transfer In'), ('MATERNITY', 'Maternity')], default='EMERGENCY', max_length=20)),
                ('admission_diagnosis', models.TextField(blank=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED_OUT', 'Transferred Out'), ('DECEASED', 'Deceased'), ('ABSCONDED', 'Absconded')], default='ADMITTED', max_length=20)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_type', models.CharField(blank=True, choices=[('NORMAL', 'Normal Discharge'), ('DAMA', 'Discharge Against Medical Advice'), ('REFERRED', 'Referred Out'), ('DECEASED', 'Deceased'), ('ABSCONDED', 'Absconded')], max_length=20)),
                ('discharge_summary', models.TextField(blank=True)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_processed', to=settings.AUTH_USER_MODEL)),
                ('admitting_doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_ordered', to=settings.AUTH_USER_MODEL)),
                ('attending_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_attending', to=settings.AUTH_USER_MODEL)),
                ('discharge_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_discharged', to=settings.AUTH_USER_MODEL)),
                ('icd10_codes', models.ManyToManyField(blank=True, related_name='admissions', to='api.icd10code')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='api.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='api.visit')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='inpatient.bed')),
            ],
            options={
                'db_table': 'admissions',
            },
        ),
        migrations.CreateModel(
            name='BedTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_transfers', to='inpatient.admission')),
                ('from_bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='inpatient.bed')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='inpatient.bed')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_transfers_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bed_transfers',
            },
        ),
        migrations.CreateModel(
            name='InpatientVitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night')], max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='inpatient.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_vitals_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inpatient_vitals',
            },
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOPICAL', 'Topical'), ('OTHER', 'Other')], default='ORAL', max_length=20)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_orders', to='inpatient.admission')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inpatient_orders', to='api.medicine')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_orders_placed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medication_orders',
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GIVEN', 'Given'), ('MISSED', 'Missed'), ('REFUSED', 'Refused'), ('HELD', 'Held')], default='GIVEN', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_administered', to=settings.AUTH_USER_MODEL)),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='inpatient.medicationorder')),
            ],
            options={
                'db_table': 'medication_administrations',
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night')], max_length=20)),
                ('note', models.TextField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='inpatient.admission')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nursing_notes',
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='inpatient.ward'),
        ),
        migrations.CreateModel(
            name='WardRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('plan', models.TextField(blank=True)),
                ('round_date', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_rounds', to='inpatient.admission')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ward_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ward_rounds',
            },
        ),
        migrations.CreateModel(
            name='BedCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('charge_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_charges', to='inpatient.admission')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='inpatient.bed')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_charges', to='api.invoice')),
            ],
            options={
                'db_table': 'bed_charges',
                'unique_together': {('admission', 'charge_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
