# Generated by Django 6.0.6 on 2026-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
