# Generated by Django 6.0.6 on 2026-07-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoice_source_type'),
        ('inpatient', '0002_medicationorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_administrations', to='api.medicinebatch'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_administrations', to='api.invoice'),
        ),
    ]
